### ISSUE TITLE
display2xl-semi-bold wrong letter spacing

### ISSUE THREAD

**Issue by Scientist-Ansh** [Dive-Into-CSS/untitled-ui#34]
### In this class this letter spacing is coming from a variable and if this variable is being reused across various classes then those classes will also have the same issue.

Please look into this @tonyblu331

**Comment by Scientist-Ansh** [comment]
Also please look into the text-xl classes,
Here,  
text-xl-reg,
text-xl-semi-bold,
text-xl-bold

all 3 classes are using the same font-weight of font weight bold which I think shouldnt be the case @tonyblu331

**Comment by tonyblu331** [comment]
Fixed the letter-spacing from 0.02em to -0.02em

Fixed the naming conventions:
- Added .ut prefix
- Fixed text-small-... classes to text-sm-...

Deleted font-family variable and properties from classes, as it was just redundant.
